# Generated by Django 4.2.4 on 2023-08-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "person_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("folder_id", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=150)),
                ("debtor", models.CharField(max_length=150)),
                ("p_num", models.CharField(max_length=150)),
                ("kind_file", models.CharField(max_length=150)),
                ("note", models.TextField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "menu_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("month", models.DateField()),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money", models.FloatField(blank=True, null=True)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.menu"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.person"
                    ),
                ),
            ],
        ),
    ]
