# Generated by Django 4.2.4 on 2023-11-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_item_money"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name": "الدوائرة", "verbose_name_plural": "الدوائرة"},
        ),
        migrations.AlterField(
            model_name="person",
            name="p_num",
            field=models.CharField(max_length=32),
        ),
    ]
