# Generated by Django 4.2.4 on 2023-11-17 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_department_options_alter_person_p_num"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "الاسماء", "verbose_name_plural": "الاسماء"},
        ),
        migrations.AlterModelOptions(
            name="menu",
            options={"verbose_name": "القوائم", "verbose_name_plural": "القوائم"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "الاضبارة", "verbose_name_plural": "الاضبارة"},
        ),
    ]
