# Generated by Django 4.2.4 on 2023-11-17 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_item_options_alter_menu_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="money",
            field=models.IntegerField(verbose_name="المبلغ"),
        ),
        migrations.AlterField(
            model_name="item",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.person",
                verbose_name="اسم الدائن",
            ),
        ),
    ]
